# Generated by Django 5.1.15 on 2026-09-25 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(help_text='Short elevator pitch or 1-line overview', max_length=255)),
                ('problem_statement', models.TextField(help_text='What problem does this project solve?')),
                ('solution_description', models.TextField(help_text='Technical explanation of the solution architecture')),
                ('github_url', models.URLField(help_text='GitHub repository link', max_length=500)),
                ('demo_url', models.URLField(blank=True, default='', help_text='Live web app or demo video link', max_length=500)),
                ('presentation_url', models.URLField(blank=True, default='', help_text='Slides, Canva, or presentation link', max_length=500)),
                ('presentation_file', models.FileField(blank=True, help_text='Optional uploaded presentation slide deck (PDF or PPT)', null=True, upload_to='submissions/presentations/')),
                ('tech_stack', models.CharField(blank=True, default='', help_text='Comma-separated technologies used', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_projects', to=settings.AUTH_USER_MODEL)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='events.team')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
