# Generated by Django 5.1.15 on 2026-09-25 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_projectsubmission_is_draft_prize_track_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='judged_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
