# Generated by Django 5.1.15 on 2026-09-25 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_judges'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Sign up, Code sprint, Submission, Problem Statement Release', max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='events.event')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
