# Generated by Django 5.1.15 on 2026-09-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventphase'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='require_demo_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='require_github_url',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='require_presentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='submission_guidelines',
            field=models.TextField(blank=True, default=''),
        ),
    ]
