# Generated by Django 5.1.15 on 2026-09-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_require_demo_url_event_require_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='github_url',
            field=models.URLField(blank=True, default='', help_text='GitHub repository link', max_length=500),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='problem_statement',
            field=models.TextField(blank=True, default='', help_text='What problem does this project solve?'),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='solution_description',
            field=models.TextField(blank=True, default='', help_text='Technical explanation of the solution architecture'),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='Short elevator pitch or 1-line overview', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
