# Generated by Django 5.1.15 on 2026-09-26 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_projectsubmission_github_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Innovation, Technical Execution, UI/UX, Presentation', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Evaluation guidelines for judges')),
                ('weight', models.FloatField(default=20.0, help_text='Weight percentage (e.g. 25 for 25%)')),
                ('max_score', models.PositiveIntegerField(default=10, help_text='Maximum mark (default 10)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='events.event')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, default='', help_text='Optional remarks or feedback notes')),
                ('total_score', models.FloatField(default=0.0, help_text='Weighted total mark (scaled 0-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='events.projectsubmission')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('submission', 'judge')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Raw mark given by judge between 1 and 10')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='events.eventrubric')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='events.projectevaluation')),
            ],
            options={
                'unique_together': {('evaluation', 'rubric')},
            },
        ),
    ]
