# Generated by Django 5.1.15 on 2026-09-26 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventrubric_projectevaluation_evaluationscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('FLAGGED', 'Flagged Outlier')], default='CREATED', max_length=20)),
                ('score_delta', models.FloatField(default=0.0, help_text='Difference between new score and previous score')),
                ('snapshot_scores', models.JSONField(default=list, help_text='List of rubric scores at time of submission')),
                ('previous_scores', models.JSONField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('is_outlier', models.BooleanField(default=False, help_text='Flagged if score diverges > 3.0 pts from consensus')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='events.projectevaluation')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_audits', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='events.projectsubmission')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Evaluation'), ('COMPLETED', 'Evaluation Completed'), ('EXCUSED', 'Excused / Reassigned')], default='PENDING', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_judges', to='events.projectsubmission')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('judge', 'submission')},
            },
        ),
    ]
