from django.urls import path
from .views import (
    AdminEventManageView,
    AdminAllTeamsView,
    AdminTeamManageView,
    AdminTeamMemberManageView,
    AdminAllSubmissionsView,
    AdminSubmissionManageView,
    AdminEventJudgeManageView,
    EventListCreateView,
    EventDetailView,
    CreateTeamView,
    JoinTeamView,
    LeaveTeamView,
    SubmitProjectView,
    MySubmissionView,
    EventSubmissionsListView,
    PublicGalleryView,
    EventRubricsManageView,
    SubmitProjectEvaluationView,
    EventLeaderboardView,
    AdminAssignJudgesView,
    AdminJudgingProgressView,
    AdminExportLeaderboardCSVView,
    AdminExportRubricsCSVView,
)

urlpatterns = [
    path('', EventListCreateView.as_view(), name='event_list_create'),
    path('<int:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('<int:pk>/teams/create/', CreateTeamView.as_view(), name='team_create'),
    path('<int:pk>/teams/join/', JoinTeamView.as_view(), name='team_join'),
    path('<int:pk>/teams/leave/', LeaveTeamView.as_view(), name='team_leave'),
    path('<int:pk>/submit/', SubmitProjectView.as_view(), name='project_submit'),
    path('<int:pk>/my-submission/', MySubmissionView.as_view(), name='my_submission'),
    path('<int:pk>/submissions/', EventSubmissionsListView.as_view(), name='event_submissions'),
    path('<int:pk>/gallery/', PublicGalleryView.as_view(), name='event_gallery'),
    path('<int:pk>/rubrics/', EventRubricsManageView.as_view(), name='event_rubrics'),
    path('<int:pk>/rubrics/<int:rubric_pk>/', EventRubricsManageView.as_view(), name='event_rubric_detail'),
    path('<int:event_pk>/submissions/<int:sub_pk>/evaluate/', SubmitProjectEvaluationView.as_view(), name='submission_evaluate'),
    path('<int:pk>/leaderboard/', EventLeaderboardView.as_view(), name='event_leaderboard'),
    path('<int:pk>/admin/assign-judges/', AdminAssignJudgesView.as_view(), name='admin_assign_judges'),
    path('<int:pk>/admin/judging-progress/', AdminJudgingProgressView.as_view(), name='admin_judging_progress'),
    path('<int:pk>/admin/export/leaderboard-csv/', AdminExportLeaderboardCSVView.as_view(), name='admin_export_leaderboard_csv'),
    path('<int:pk>/admin/export/rubrics-csv/', AdminExportRubricsCSVView.as_view(), name='admin_export_rubrics_csv'),

    path('admin/events/<int:pk>/', AdminEventManageView.as_view(), name='admin_event_manage'),
    path('admin/events/<int:pk>/judges/', AdminEventJudgeManageView.as_view(), name='admin_event_judge_manage'),
    path('admin/teams/', AdminAllTeamsView.as_view(), name='admin_all_teams'),
    path('admin/teams/<int:pk>/', AdminTeamManageView.as_view(), name='admin_team_manage'),
    path('admin/teams/<int:team_pk>/members/<int:user_pk>/', AdminTeamMemberManageView.as_view(), name='admin_team_member_manage'),
    path('admin/submissions/', AdminAllSubmissionsView.as_view(), name='admin_all_submissions'),
    path('admin/submissions/<int:pk>/', AdminSubmissionManageView.as_view(), name='admin_submission_manage'),
]

